Feature/gha
ool-mddo/playground pull request #2
Opened 2022-04-22 07:47 UTC by t-tkgh

2022-04-25 02:40 UTC, corestate55 requested changes
* .env についてはPRから外してください(環境固有の値が入っているので)
* pushed_flagの使い方について確認させてください。pushed_config リポジトリとの連携とか全体の動作がよくわからず…

2022-04-25 02:40 UTC, corestate55 commented on .env
> -FISH_TRACER_BASE_URL=http://IP-or-FQDN:15000
環境固有の設定が入っちゃってるのでこれは除外してもらえますか?

2022-04-25 02:40 UTC, corestate55 commented on .github/workflows/generate_topo.yml
> +          git checkout -b `ls -1 ../../pushed_flag/` origin/`ls -1 ../../pushed_flag/`
pushed_flag の使い方確認させてください。(よくわからなくなってしまった…) 誰が、どのタイミングで、何を設定するんでしたっけ?

2022-04-26 02:55 UTC, bgl-tkgh commented on .env
> -FISH_TRACER_BASE_URL=http://IP-or-FQDN:15000
> 環境固有の設定が入っちゃってるのでこれは除外してもらえますか?

修正しました。

2022-04-26 02:56 UTC, t-tkgh commented on .env
> -FISH_TRACER_BASE_URL=http://IP-or-FQDN:15000
修正しました。

2022-04-26 05:50 UTC, corestate55 commented on .github/workflows/generate_topo.yml
> +          git checkout -b `ls -1 ../../pushed_flag/` origin/`ls -1 ../../pushed_flag/`
こんな感じでしょうか
![flow](https://user-images.githubusercontent.com/20035048/165230386-16c6b871-7306-41c5-b70f-e52310d8032b.png)
[pushed_configs, generate_topo.yml](https://github.com/ool-mddo/pushed_configs/blob/feature/generate_topology/.github/workflows/generate_topo.yml ) 
* `feature/gha` branch にプッシュする?
* `flag` / `flag` 混在しているところがありそうなのですが大丈夫ですか?

2022-04-26 05:50 UTC, corestate55 commented on .github/workflows/generate_topo.yml
> +          git checkout -b `ls -1 ../../pushed_flag/` origin/`ls -1 ../../pushed_flag/`
こんな感じでしょうか
![flow](https://user-images.githubusercontent.com/20035048/165230386-16c6b871-7306-41c5-b70f-e52310d8032b.png)
[pushed_configs, generate_topo.yml](https://github.com/ool-mddo/pushed_configs/blob/feature/generate_topology/.github/workflows/generate_topo.yml ) 
* `feature/gha` branch にプッシュする?
* `flag` / `flag` 混在しているところがありそうなのですが大丈夫ですか?

2022-04-26 11:36 UTC, t-tkgh commented on .github/workflows/generate_topo.yml
> +          git checkout -b `ls -1 ../../pushed_flag/` origin/`ls -1 ../../pushed_flag/`
イメージ図作成ありがとうございます。動作シーケンスはあっています。
pushed_configの方はまだ修正未反映でして、コミットするブランチも202202demoで固定してしまっているので、ここも実行しているブランチ名を環境変数から取得するようにする予定です。
Playgroundのプルリクをマージ次第、pushed_configの修正を反映しようと思います。

2022-05-14 02:41 UTC, merged